### ISSUE TITLE
Feature : Comment out the subheadings in the issue templates

### ISSUE THREAD

**Issue by epicadk** [anitab-org/.github#1]
### Is your feature request related to a problem? Please describe.

Comment out the subheadings in the issue to that it looks cleaner when rendered on github. 
Same issue as [this issue](https://github.com/anitab-org/mentorship-android/issues/1039) which was opened on the mentorship android repo

### Describe the solution you'd like

A similar fix should be applied here as well.

**Comment by epicadk** [comment]
@isabelcosta can you check if this is a valid issue 😅

**Comment by annabauza** [comment]
approved

**Comment by prykdev** [comment]
I'd like to work on this if it is available. : )

**Comment by annabauza** [comment]
Yours @P-riyanka-prasad

**Comment by prykdev** [comment]
I have gone throug this repo but i didnt get one thing what i need to edit all the repo
https://github.com/anitab-org/.github/tree/main/.github/ISSUE_TEMPLATE And here
https://github.com/anitab-org/.github/tree/main/.github
is alrady documented Then what i need to comment out or document??

**Comment by epicadk** [comment]
https://github.com/anitab-org/mentorship-android/issues/1039 you can take a look here it was a similar issue.

**Comment by prykdev** [comment]
Can anyone check is the pull request i have made is correct ?
https://github.com/anitab-org/.github/pull/6#issue-597297386

**Comment by Rahulm2310** [comment]
@isabelcosta This can be closed as PR for this is already merged.
